import json

with open('lexicon.json', 'r') as fp:
    lexicon = json.load(fp)

with open('../../../magma/lexica/TestCoverageLexicon.gf', 'w') as abstract, \
        open('../../../magma/lexica/TestCoverageLexiconEng.gf', 'w') as concrete:
    abstract.write('''-- This file is autogenerated
abstract TestCoverageLexicon = FreeArgs ** {
    cat
        Noun;
        Adjective;
    fun
        noun_to_prekind : Noun -> PreKind;
        compound_noun : Noun -> Noun -> Noun;
        compound_noun_v1 : Noun -> Noun -> Noun;
        
        adjective_to_property : Adjective -> Property;
        hyphenated_adj_adj : Adjective -> Adjective -> Adjective;
        
        lex_argmark_by : ArgMarker;
        lex_argmark_of : ArgMarker;
        lex_argmark_from : ArgMarker;
        lex_argmark_to : ArgMarker;
        lex_argmark_on : ArgMarker;
        lex_argmark_in : ArgMarker;
        lex_argmark_under : ArgMarker;
        lex_with_respect_to : ArgMarker;
        lex_with_respect_to_v1 : ArgMarker;
''')

    concrete.write(r'''-- This file is autogenerated
concrete TestCoverageLexiconEng of TestCoverageLexicon = FreeArgsEng ** open ParadigmsEng, SyntaxEng, GrammarEng, ResEng in {
    oper
        adj_table_prefix : Str -> (AForm => Str) -> (AForm => Str) = \prefix, forms -> table { aform => prefix ++ (forms ! aform) };

    lincat
        Noun = N;
        Adjective = A;
    lin
        noun_to_prekind noun = mkCN noun;
        compound_noun n1 n2 = mkN (n1.s ! Sg ! Nom) n2;
        compound_noun_v1 n1 n2 = mkN (n1.s ! Sg ! Nom ++ "-") n2;
        
        adjective_to_property adj = mkAP adj;
        hyphenated_adj_adj adj1 adj2 = lin A {s = adj_table_prefix (adj1.s ! AAdj Posit Nom) adj2.s; isPre = adj2.isPre; isMost = adj2.isMost};

        lex_argmark_by = mkPrep "by";
        lex_argmark_of = mkPrep "of";
        lex_argmark_from = mkPrep "from";
        lex_argmark_to = mkPrep "to";
        lex_argmark_on = mkPrep "on";
        lex_argmark_in = mkPrep "in";
        lex_argmark_under = mkPrep "under";
        lex_with_respect_to = mkPrep "with respect to";
        lex_with_respect_to_v1 = mkPrep "w.r.t.";
''')

    abstract.write('\n-- Prekinds\n')
    for noun, forms in lexicon['N'].items():
        forms = [f.replace('-', ' - ') for f in forms]
        symb = f'noun_lex_{noun}'
        abstract.write(f'        {symb} : Noun;\n')
        concrete.write(f'        {symb} = mkN "{forms[0]}" "{forms[1]}";\n')

    abstract.write('\n-- PrePredicates\n')
    for verb, forms in lexicon['V'].items():
        forms = [f.replace('-', ' - ') for f in forms]
        symb = f'pp_lex_{verb}'
        abstract.write(f'        {symb} : PrePredicate;\n')
        concrete.write(f'        {symb} = mkV "{forms[0]}" "{forms[1]}";\n')

    abstract.write('\n-- Properties\n')
    for adj, forms in lexicon['A'].items():
        forms = [f.replace('-', ' - ') for f in forms]
        symb = f'prop_lex_{adj}'
        abstract.write(f'        {symb} : Adjective;\n')
        concrete.write(f'        {symb} = mkA "{forms[0]}";\n')

    # abstract.write('\n-- ProperNames\n')

    abstract.write('}\n')
    concrete.write('}\n')


    
